spring:
  application:
    name: asyncTask
  datasource:
    hikari:
      username:
      password:
      driver-class-name:
      jdbc-url:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

thirdPart:
  redis:
    endPoint: 127.0.0.1:6379